#!/bin/bash

# a quick script to record command lines for break-point analysis

### Note:
###   The "fitting bins" overlap, but do not actually include the "next nearest" moment.
###   This should help visualize the scale at which the power laws actually break?

w4t-compute-moments \
    ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
    M05MA10-test-moments.hdf \
    --max-edgelength 512 \
    --polyfit 1 \
    --polyfit-scales 2 15 \
    --polyfit-scales 9 200 \
    -f vel -f vort -f dens -f mag -f curr \
    --Verbose \
|| exit 1

w4t-plot-moments \
    M05MA10-test-moments.hdf \
    --Verbose \
|| exit 1
