#!/bin/bash

# a simple command line
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

echo \
/usr/bin/time -v \
./test \
    --path ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
    --field dens \
    --field mag \
    --field vel \
    --max-edgelength 512 \
    --verbose \
|| exit 1

#---

echo \
/usr/bin/time -v \
./plot \
     --path ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
     --output-dir M05MA10 \
     --tag Turb_hdf5_plt_cnt_0050 \
     --field dens \
     --field mag \
     --field vel \
     --max-edgelength 512 \
     --scatter-quantile 0.99 \
     --verbose \
|| exit 1

#---

# examine scaling with grid size for different numbers of dimensions

echo \
/usr/bin/time -v \
./test-scaling \
    2 268435456 \
    --num-dim 1 \
    --num-trials 100 \
    --output-dir scaling \
    --tag num-dim_1 \
    --Verbose \
|| exit 1

echo \
/usr/bin/time -v \
./test-scaling \
    2 4096 \
    --num-dim 2 \
    --num-trials 100 \
    --output-dir scaling \
    --tag num-dim_2 \
    --Verbose \
|| exit 1

echo \
/usr/bin/time -v \
./test-scaling \
    2 512 \
    --num-dim 3 \
    --num-trials 100 \
    --output-dir scaling \
    --tag num-dim_3 \
    --Verbose \
|| exit 1
