#!/bin/bash

# a simple command line
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

echo \
./test \
    --path ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
    --field dens \
    --field mag \
    --field vel \
    --max-edgelength 512 \
    --verbose \
|| exit 1

#---

echo \
./plot \
     --path ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
     --output-dir M05MA10 \
     --tag Turb_hdf5_plt_cnt_0050 \
     --field dens \
     --field mag \
     --field vel \
     --max-edgelength 512 \
     --scatter-quantile 0.99 \
     --verbose \
|| exit 1

#---

# set up a loop to iterate through different data sizes

echo \
./test-scaling \
    --num-grid 32 \
    --verbose \
|| exit 1
