#!/bin/bash

# a simple command line
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

echo \
/usr/bin/time -v \
./test \
    --path ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
    --field dens \
    --field mag \
    --field vel \
    --max-edgelength 512 \
    --verbose \
|| exit 1

#---

echo \
/usr/bin/time -v \
./plot \
     --path ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
     --output-dir M05MA10 \
     --tag Turb_hdf5_plt_cnt_0050 \
     --field dens \
     --field mag \
     --field vel \
     --max-edgelength 512 \
     --scatter-quantile 0.99 \
     --verbose \
|| exit 1

#---

# set up a loop to iterate through different data sizes

grid=1

for n2 in $(seq 1 6)
do

    grid=$(($grid * 2))

    echo ">> grid = $grid"

    echo \
    /usr/bin/time -v \
    ./test-scaling \
        --num-grid $grid \
        --num-trials 100 \
        --verbose \
    || exit 1

done
