#!/bin/bash

# test basic workflows
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

# convert the file format on disk to be faster to load

echo \
w4t-convert-flash \
    ../data/M05MA10/Turb_hdf5_plt_cnt_0050 \
    ../data/M05MA10/M05MA10_0050.hdf \
    vel vort mag curr dens \
    --Verbose \
|| exit 1

#------------------------

# compute structure function

#echo \
w4t-structure-function \
    ../data/M05MA10/M05MA10_0050.hdf \
    ../data/M05MA10/M05MA10_0050-structure-function.hdf \
    vel \
    --component 0 \
    --max-edgelength 512 \
    --index 1 2 3 4 \
    --Verbose \
|| exit 1

#------------------------

# denoise to identify coherent structures

echo \
w4t-denoise \
    ../data/M05MA10/M05MA10_0050.hdf \
    ../data/M05MA10/M05MA10_0050-denoise.hdf \
    vel \
    --component 0 \
    --max-edgelength 512 \
    --wavelet haar \
    --threshold 2.0 \
    --max-scale 256 \
    --verbose \
|| exit 1

#-----------

# compute structure function of denoised flow

#echo \
w4t-structure-function \
    ../data/M05MA10/M05MA10_0050-denoise.hdf \
    ../data/M05MA10/M05MA10_0050-denoise-structure-function.hdf \
    vel_0 \
    --max-edgelength 512 \
    --index 1 2 3 4 \
    --Verbose \
|| exit 1

#-----------

# identify structures as separate sets of pixels

echo \
w4t-structures \
    ../data/M05MA10/M05MA10_0050-denoise.hdf \
    ../data/M05MA10/M05MA10_0050-denoise-structures.hdf \
    vel_0 \
    --wavelet haar \
    --max-edgelength 256 \
    --threshold 3.0 \
    --num-proc 4 \
    --verbose \
|| exit 1
