#!/bin/bash

### install supporting libraries
### Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

OPTDIR="opt"
mkdir -p $OPTDIR

#------------------------

# install FLASH wrappers from James Beattie (jbeattie@cita.utoronto.ca)

pushd $OPTDIR
git clone https://github.com/AstroJames/PLASMAtools.git
popd

#------------------------

# install PyWavelets
for package in numpy scipy matplotlib PyWavelets
do
    pip install $package --prefix $OPTDIR --force-reinstall
done

#------------------------

# install this module
pip install . --prefix $OPTDIR
