#!/bin/bash

# a simple script to iterate over boxes and compute moments for each
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

BASEDIR="/fs/lustre/project/plasmaastro/jbeattie/turbulent_boxes/"

SIMS=$(ls $BASEDIR/M*MA*/Turb_hdf5_plt_cnt_0050 | awk -F '/' '{print $9}') # WARNING! this is probably very fragile
#SIMS="M05MA10" # for testing purposes

#-------------------------------------------------

for SIM in $SIMS
do

    echo "processing: $SIM"

    #---

    # clean up any previous runs
    rm -r $SIM 
    mkdir $SIM

    # iterate over snapshots, computing moments of each
#    cp -v $BASEDIR/$SIM/Turb_hdf5_plt_cnt_???? $SIM
    ln -s $BASEDIR/$SIM/Turb_hdf5_plt_cnt_???? $SIM

done
