#!/bin/bash

# a simple script to iterate over boxes and compute moments for each
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

BASEDIR="/fs/lustre/project/plasmaastro/jbeattie/turbulent_boxes/"

SIMS=$(ls $BASEDIR/M*MA*/Turb_hdf5_plt_cnt_0050 | awk -F '/' '{print $9}') # WARNING! this is probably very fragile

#-------------------------------------------------

for SIM in $SIMS
do

    echo "processing: $SIM"

    #---

    # clean up any previous runs
    rm -r $SIM 
    mkdir $SIM

    # iterate over snapshots, computing moments of each
    for INPATH in $(ls $BASEDIR/$SIM/Turb_hdf5_plt_cnt_????)
    do

	OUTPATH="$SIM/moments-$(echo $INPATH | awk -F '/' '{print $10}').hdf"

	echo \
	w4t-compute-moments \
	    $INPATH \
	    $OUTPATH \
	    --moments 2 3 4 5 6 \
            --field dens \
            --field mag \
            --field vel \
            --max-edgelength 512 \
            --verbose \
       || exit 1

    done

done
