#!/bin/bash

# a simple script to iterate over boxes and compute moments for each
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

SIMS=$(ls M*MA* -d) # iterate over all boxes
#SIMS="M05MA10" # for testing purposes

#-------------------------------------------------

for SIM in $SIMS
do

    echo "processing: $SIM"

    #---

    # iterate over snapshots, computing moments of each
    for INPATH in $(ls $SIM/Turb_hdf5_plt_cnt_????)
    do

	OUTPATH="$SIM/moments-$(echo $INPATH | awk -F '/' '{print $2}').hdf"

	echo \
	w4t-compute-moments \
	    $INPATH \
	    $OUTPATH \
	    --moments 2 3 4 5 6 \
            --field dens \
            --field mag \
            --field vel \
            --max-edgelength 512 \
            --verbose \
       || exit 1

    done

done
