#!/bin/bash

# a simple script to iterate over boxes and compute moments for each
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

#SIMS=$(ls M*MA* -d) # iterate over all boxes

#---

# for testing purposes

SIMS=""

SIMS="$SIMS M05MA01"
SIMS="$SIMS M05MA05"
#SIMS="$SIMS M05MA10"

SIMS="$SIMS M10MA01"
SIMS="$SIMS M10MA05"
SIMS="$SIMS M10MA10"

#-------------------------------------------------

for SIM in $SIMS
do

    echo "processing: $SIM"

    #---

    # iterate over snapshots, computing moments of each
    for INPATH in $(ls $SIM/Turb_hdf5_plt_cnt_????)
    do

	OUTPATH="$SIM/moments-$(echo $INPATH | awk -F '/' '{print $2}').hdf"

#	echo \
	w4t-compute-moments \
	    $INPATH \
	    $OUTPATH \
	    --moments 2 3 4 5 6 \
            --field dens \
            --field mag \
            --field vel \
            --max-edgelength 512 \
            --verbose \
        || exit 1

#	echo \
        w4t-plot-moments \
	    $OUTPATH \
	    --verbose \
	|| exit 1

    done

    #---

    # average over snapshots

    OUTPATH="$SIM/moments-Turb_hdf5_plt_cnt_average.hdf"

#    echo \
    w4t-average-moments \
        $(ls $SIM/moments-Turb_hdf5_plt_cnt_????.hdf) \
        --outpath $OUTPATH \
	--Verbose \
    || exit 1

#    echo \
    w4t-plot-moments \
        $OUTPATH \
        --verbose \
    || exit 1

done
