#!/bin/bash

# a simple script to store command lines
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

data="b_field-wavelet_turbulence-2025-02-22.npy"

thr2d=3.0 # used for denoising
thr1d=1.0 # used for denoising

#-------------------------------------------------

ARGS="--figtype png --figtype pdf --dpi 500"
ZOOM="--zoom 0.28 0.45 0.45 0.55"

#-------------------------------------------------

for wavelet in "db1"
do

    ### 2D ANALYSIS

    # regular decomposition

    echo \
    ./analyze-2d \
        $data \
        --wavelet $wavelet \
        --log \
        --Verbose \
        --output-dir $wavelet \
        --tag $wavelet \
        $ARGS \
        $ZOOM \
    || exit 1

    # denoise

    echo \
    ./analyze-2d \
        $data \
        --wavelet $wavelet \
        --log \
        --denoise $thr2d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn${thr2d} \
        $ARGS \
        $ZOOM \
    || exit 1

    # smooth

    echo \
    ./analyze-2d \
        $data \
        --wavelet $wavelet \
        --log \
        --denoise $thr2d \
        --smooth \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn${thr2d}_smooth \
        $ARGS \
        $ZOOM \
    || exit 1

    #--------------------

    ### COMBO ANALYSIS

    # regular decomposition

#    echo \
    ./analyze-fancy \
        $data \
        --wavelet $wavelet \
        --log \
        --Verbose \
        --output-dir $wavelet \
        --tag $wavelet \
        $ARGS \
        $ZOOM \
    || exit 1

    # denoise

#    echo \
    ./analyze-fancy \
        $data \
        --wavelet $wavelet \
        --log \
        --denoise $thr2d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn${thr2d} \
        $ARGS \
        $ZOOM \
    || exit 1

    # smooth

#    echo \
    ./analyze-fancy \
        $data \
        --wavelet $wavelet \
        --log \
        --denoise $thr2d \
        --smooth \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn${thr2d}_smooth \
        $ARGS \
        $ZOOM \
    || exit 1

    #--------------------

    ### 1D ANALYSIS

    # regular decomposition

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --Verbose \
        --output-dir $wavelet \
        --tag $wavelet \
        $ARGS \
    || exit 1

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-1d $thr1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn1d${thr1d} \
        $ARGS \
    || exit 1

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-1d $thr1d \
        --smooth-1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn1d${thr1d}_smooth \
        $ARGS \
    || exit 1

    #---

    # denoise

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-2d $thr2d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr2d} \
        $ARGS \
    || exit 1

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-2d $thr2d \
        --denoise-1d $thr1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr2d}_dn1d${thr1d} \
        $ARGS \
    || exit 1

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-2d $thr2d \
        --denoise-1d $thr1d \
        --smooth-1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr2d}_dn1d${thr1d}_smooth \
        $ARGS \
    || exit 1

    #---

    # smooth

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-2d $thr2d \
        --smooth-2d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr2d}_smooth \
        $ARGS \
    || exit 1

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-2d $thr2d \
        --smooth-2d \
        --denoise-1d $thr1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr2d}_smooth_dn1d${thr1d} \
        $ARGS \
    || exit 1

    echo \
    ./analyze-1d \
        $data \
        --abs \
        --wavelet $wavelet \
        --denoise-2d $thr2d \
        --smooth-2d \
        --denoise-1d $thr1d \
        --smooth-1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr2d}_smooth_dn1d${thr1d}_smooth \
        $ARGS \
    || exit 1

done
