#!/bin/bash

# a simple script to store command lines
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

data="b_field-wavelet_turbulence-2025-02-22.npy"
thr=2 # used for denoising

#-------------------------------------------------

for wavelet in "db1"
do

    ### 2D ANALYSIS

    # regular decomposition

#    echo \
    ./analyze-2d \
        $data \
        --wavelet $wavelet \
        --Verbose \
        --output-dir $wavelet \
        --tag $wavelet \
    || exit 1

    # denoise

#    echo \
    ./analyze-2d \
        $data \
        --wavelet $wavelet \
        --denoise $thr \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn${thr} \
    || exit 1

    # smooth

#    echo \
    ./analyze-2d \
        $data \
        --wavelet $wavelet \
        --denoise $thr \
        --smooth \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn${thr}_smooth \
    || exit 1

    #--------------------

    ### 1D ANALYSIS

    # regular decomposition

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --Verbose \
        --output-dir $wavelet \
        --tag $wavelet \
    || exit 1

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-1d $thr \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn1d${thr} \
    || exit 1

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-1d $thr \
        --smooth-1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn1d${thr}_smooth \
    || exit 1

    #---

    # denoise

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-2d $thr \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr} \
    || exit 1

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-2d $thr \
        --denoise-1d $thr \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr}_dn1d${thr} \
    || exit 1

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-2d $thr \
        --denoise-1d $thr \
        --smooth-1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr}_dn1d${thr}_smooth \
    || exit 1

    #---

    # smooth

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-2d $thr \
        --smooth-2d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr}_smooth \
    || exit 1

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-2d $thr \
        --smooth-2d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr}_smooth_dn1d${thr} \
    || exit 1

#    echo \
    ./analyze-1d \
        $data \
        --wavelet $wavelet \
        --denoise-2d $thr \
        --smooth-2d \
        --denoise-1d $thr \
        --smooth-1d \
        --Verbose \
        --output-dir $wavelet \
        --tag ${wavelet}_dn2d${thr}_smooth_dn1d${thr}_smooth \
    || exit 1

done
