#!/usr/bin/env python3

"""a magical script to identify X and O points
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import os

import numpy as np
import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

from argparse import ArgumentParser

### non-standard libraries
from w4t import pywt
from w4t.plot import plane as plt

from w4t.utils import dv # PLASMAtools.aux_funcs.derived_var_funcs

#-------------------------------------------------

x_logmag_thr = -1.75
x_x_thr      = +0.01
x_o_thr      = +1.75

o_logmag_thr = -1.20
o_x_thr      = +0.01
o_o_thr      = +1.75

#-------------------------------------------------

def extrema(data):
    """find local extrema neglecting pixels at the edge of the simulation
    """
    mins = np.ones((nx, ny), dtype=bool)
    maxs = np.ones((nx, ny), dtype=bool)

    mins[0,:] = mins[-1,:] = mins[:,0] = mins[:,-1] = False # exclude edge points
    maxs[0,:] = maxs[-1,:] = maxs[:,0] = maxs[:,-1] = False

    for i in range(nx-2): # look for local minima in the x-direction
        mins[i+1,:] *= (data[i,:] > data[i+1,:])*(data[i+1,:] < data[i+2,:]) # check x derivative
        maxs[i+1,:] *= (data[i,:] < data[i+1,:])*(data[i+1,:] > data[i+2,:])

    for j in range(ny-2): # look for local minima in the y-direction
        mins[:,j+1] *= (data[:,j] > data[:,j+1])*(data[:,j+1] < data[:,j+2])
        maxs[:,j+1] *= (data[:,j] < data[:,j+1])*(data[:,j+1] > data[:,j+2])

    low = np.arange(0, nx-2)
    mid = low+1
    hgh = mid+1
    for i in range(nx-2): # look for local minima along diagonals
        mins[i+1,mid] *= (data[i,low] > data[i+1,mid])*(data[i+1,mid] < data[i+2,hgh]) # check diagonal
        mins[i+1,mid] *= (data[i,hgh] > data[i+1,mid])*(data[i+1,mid] < data[i+2,low]) # check diagonal

        maxs[i+1,mid] *= (data[i,low] < data[i+1,mid])*(data[i+1,mid] > data[i+2,hgh]) # check diagonal
        maxs[i+1,mid] *= (data[i,hgh] < data[i+1,mid])*(data[i+1,mid] > data[i+2,low]) # check diagonal

    return mins, maxs

#------------------------

def imshow_mag(mag, o, x, mins, aspect='auto', orad=None):
    fig = plt.plt.figure(figsize=(10,5))

    ax = fig.add_axes([0.025, 0.05, 0.95, 0.90])

    logmag = np.log10(mag)
    vmax = np.max(logmag)
    vmin = max(np.min(logmag), vmax-3)

    ax.imshow(
        logmag,
        cmap='vanimo',
        vmin=vmin,
        vmax=vmax,
        aspect=aspect,
        origin='lower',
        extent=(0, 1, 0, 1),
    )

    ax.set_xticks(np.arange(0, 1+0.05, 0.05))
    ax.set_xlim(0, 1)

    ax.set_yticks(ax.get_xticks())
    ax.set_ylim(0, 1)
#    ax.set_ylim(0.45, 0.55)

    ax.set_title('$\log|B|$')

    xmins = mins * (logmag < x_logmag_thr) * (x < x_x_thr) * (o > x_o_thr)
    omins = mins * (logmag < o_logmag_thr) * (x > o_x_thr) * (o < o_o_thr)

    nx, ny = mag.shape
    xs = (0.5+np.arange(nx)) / nx
    ys = (0.5+np.arange(ny)) / ny
    X, Y = np.meshgrid(xs, ys)

    ax.contour(X, Y, logmag, colors='w', linewidths=0.1, alpha=0.50, levels=np.linspace(vmin, vmax, 101))

    # plot minima that we think might be Xs
    ax.plot(X[xmins], Y[xmins], marker='x', markersize=4, markeredgewidth=0.75, color='w', alpha=0.5, linestyle='none')

    # plot minima that we think might be Os
    ax.plot(X[omins], Y[omins], marker='o', markersize=4, markeredgewidth=0.75, markeredgecolor='w', markerfacecolor='none', alpha=0.5, linestyle='none')

    if orad is not None:
        nx, ny = mag.shape
        t = np.linspace(0, 2*np.pi, 101)
        ct = np.cos(t)
        st = np.sin(t)
        for X, Y, R in orad:
            if R > 10: ### FIXME remove ad hoc threshold
                ax.plot((Y+0.5)/ny, (X+0.5)/nx, color='k', marker='o', markersize=2) # mark this point as special
            ax.plot((Y+0.5+R*st)/ny, (X+0.5+R*ct)/nx, color='k', alpha=0.50, linewidth=0.5) # plot in this silly way to match imshow

    ax.tick_params(
        left=True,
        right=True,
        top=True,
        bottom=True,
        which='both',
        direction='in',
    )

    plt.plt.setp(ax.get_xticklabels(), visible=False)
    plt.plt.setp(ax.get_yticklabels(), visible=False)

    return fig

#------------------------

def imshow(curr, curr_denoise, mag, mag0, mag1, o, x, div, det, mins, maxs, aspect='auto'):
    fig = plt.plt.figure(figsize=(15,5))

    sel = np.abs(curr_denoise) > 0

    #---

    logcurr = np.log10(np.abs(curr))
#    logcurr_vmax = None
#    logcurr_vmin = None
    logcurr_vmax = np.max(logcurr)
    logcurr_vmin = max(np.min(logcurr), logcurr_vmax-3)

    logcurr_denoise = np.log10(np.abs(curr_denoise))

    logmag = np.log10(np.abs(mag))
#    logmag_vmax = None
#    logmag_vmin = None
    logmag_vmax = np.max(logmag)
    logmag_vmin = max(np.min(logmag), logmag_vmax-3)

    logdiv = np.log10(np.abs(div)) - logmag # normalize this
    logdiv_vmax = None
    logdiv_vmin = None

    sgndet = np.sign(det)
    sgndet_vmax = 1
    sgndet_vmin = -1

#    logdet = np.log10(np.abs(det))
#    logdet_vmax = None
#    logdet_vmin = None
#    logdet_vmax = np.max(np.abs(logdet))
#    logdet_vmin = max(np.min(logdet), logdet_vmax-3)

    bx_vmax = +1
    bx_vmin = -1

    by_vmax = +1
    by_vmin = -1

    logo = np.log10(o)
    logo_vmin = None
    logo_vmax = None
#    logo_vmin = np.min(logo[logo==logo]) # be careful about nans
#    logo_vmax = min(np.max(logo[logo==logo]), logo_vmin+5)

    logx = np.log10(x)
    logx_vmin = None
    logx_vmax = None

    #---

    nx, ny = mag.shape
    xs = (0.5+np.arange(nx)) / nx
    ys = (0.5+np.arange(ny)) / ny
    X, Y = np.meshgrid(xs, ys)

    xmins = mins * sel * (logmag < x_logmag_thr) * (x < x_x_thr) * (o > x_o_thr)
    omins = mins * sel * (logmag < o_logmag_thr) * (x > o_x_thr) * (o < o_o_thr)

#    xmins = mins * sel * (logmag < -1.2) * (sgndet < 0) # do this based on just the sign of det|d_i B_j| and where |B| ~ 0
#    omins = mins * sel * (logmag < -1.2) * (sgndet > 0)

    #---

    datas = [
        ('$\log|j|$', 'Greys', logcurr, np.ones_like(curr, dtype=bool), logcurr_vmin, logcurr_vmax),
        ('$B_y/|B|$', 'RdBu', mag0/mag, np.ones_like(mag0, dtype=bool), by_vmin, by_vmax),
        ('$B_x/|B|$', 'RdBu', mag1/mag, np.ones_like(mag1, dtype=bool), bx_vmin, bx_vmax),
        ('$\log o$', 'Greys_r', logo, np.ones_like(logo, dtype=bool), logo_vmin, logo_vmax),
        ('$\log x$', 'Greys_r', logx, np.ones_like(logx, dtype=bool), logx_vmin, logx_vmax),
#        ('$\log|\sum_i \partial_i B_i| - \log|B|$', 'YlGn_r', logdiv, np.ones_like(logdiv, dtype=bool), logdiv_vmin, logdiv_vmax),
#        ('$\log|\mathrm{det}|\partial_i B_j||$', 'YlGn_r', logdet, np.ones_like(logdet, dtype=bool), logdet_vmin, logdet_vmax),
        ('$\mathrm{sgn}(\mathrm{det}|\partial_i B_j|)$', 'PuOr', sgndet, np.ones_like(sgndet, dtype=bool), sgndet_vmin, sgndet_vmax),
        ('$\log|B|$', 'vanimo', logmag, np.ones_like(mag, dtype=bool), logmag_vmin, logmag_vmax),
    ]

    num_datas = len(datas)

    #---

    zoomy= True
    zoomx= False

    ylim = 0.45, 0.55

#    xlim = 0.25, 0.45 # a big plasmoid
    xlim = 0.50, 0.75 # multiple smaller plasmoids

    #---

    for ind, (label, cmap, data, ect, vmin, vmax) in enumerate(datas):
        if np.prod(data.shape) == 0: continue

        axs = []

        ax = plt.plt.subplot(2,num_datas,ind+1)
        ax.imshow(
            data,
            cmap=cmap,
            vmax=vmax,
            vmin=vmin,
            aspect=aspect,
            origin='lower',
            extent=(0, 1, 0, 1),
        )

        ax.set_title(label)

        axs.append(ax)

        #---

        ax = plt.plt.subplot(2,num_datas,num_datas+ind+1)
        ax.imshow(
            np.where(sel, data, np.nan),
            cmap=cmap,
            vmax=vmax,
            vmin=vmin,
            aspect=aspect,
            origin='lower',
            extent=(0, 1, 0, 1),
        )

        # plot all extrema
        ax.plot(X[mins], Y[mins], marker='.', markersize=1, color='r', alpha=0.25, linestyle='none')
        ax.plot(X[maxs], Y[maxs], marker='.', markersize=1, color='b', alpha=0.25, linestyle='none')

        # plot minima that we think might be Xs
        ax.plot(X[xmins], Y[xmins], marker='x', markersize=4, markeredgewidth=0.75, color='w', alpha=0.5, linestyle='none')

        # plot minima that we think might be Os
        ax.plot(X[omins], Y[omins], marker='o', markersize=4, markeredgewidth=0.75, markeredgecolor='w', markerfacecolor='none', alpha=0.5, linestyle='none')

        axs.append(ax)

        #---

        for ax in axs:
            ax.tick_params(**plt.IMSHOW_TICK_PARAMS)

            plt.plt.setp(ax.get_xticklabels(), visible=False)
            plt.plt.setp(ax.get_yticklabels(), visible=False)

            if zoomy:
                ax.set_ylim(ylim)
            if zoomx:
                ax.set_xlim(xlim)

    #---

    # finish decorating

    plt.plt.subplots_adjust(
        left=0.01,
        right=0.99,
        bottom=0.05,
        top=0.90,
        hspace=0.03,
        wspace=0.03,
    )

    #---

    return fig

#------------------------

def hist(mins, maxs, sel, mag, o, x):
    fig = plt.plt.figure(figsize=(5,5))

    #--- define data

    logmag = np.log10(mag)
    data = [logmag, o, x]
    labels = ['$\log|B|$', '$o$', '$x$']

    #--- define subsets

    everything = np.ones_like(sel, dtype=bool)
    structure = sel

    #--- iterate and build-up corner plot

    num = len(data)

    add_label = True
    colors = dict()

    selections = [
        ('k', 'everything', 'coherent structure', everything),
        ('b', 'minima', 'minima in coherent structure', mins),
        ('r', 'maxima', 'maxima in coherent structure', maxs),
    ]

    for row in range(num):
        for col in range(row): # joint distribution --> scatter plot
            ax = plt.plt.subplot(num, num, num*row+col+1)

            X = data[col]
            Y = data[row]

            for ind, (color, label1, label2, ect) in enumerate(selections):
                ax.plot(np.ravel(X[ect]), np.ravel(Y[ect]), marker='.', markersize=1, linestyle='none', alpha=0.05, color=color)
                ax.plot(np.ravel(X[ect*sel]), np.ravel(Y[ect*sel]), marker='o', markersize=4, linestyle='none', alpha=0.05, markeredgecolor=color, markerfacecolor='none')


                if add_label:
                    fig.text(0.95, 0.95-0.025*(2*ind), '%s (%d)' % (label1, np.sum(ect)), color=color, ha='right', va='top', fontsize=8)
                    fig.text(0.95, 0.95-0.025*(2*ind+1), '%s (%d)' % (label2, np.sum(ect*sel)), color=color, ha='right', va='top', fontsize=8)

            add_label = False

            if row != num-1:
                plt.plt.setp(ax.get_xticklabels(), visible=False)
            else:
                ax.set_xlabel(labels[col])

            if col != 0:
                plt.plt.setp(ax.get_yticklabels(), visible=False)
            else:
                ax.set_ylabel(labels[row])

            # add annotations for thresholds
            if row == 0: # logmag
                xlim = ax.get_xlim()
                ax.plot(xlim, [x_logmag_thr]*2, color='grey', linestyle='solid', alpha=0.50)
                ax.plot(xlim, [o_logmag_thr]*2, color='grey', linestyle='dashed', alpha=0.50)
                ax.set_xlim(xlim)

            elif row == 1:
                xlim = ax.get_xlim()
                ax.plot(xlim, [o_o_thr]*2, color='grey', linestyle='dashed', alpha=0.50)
                ax.plot(xlim, [x_o_thr]*2, color='grey', linestyle='solid', alpha=0.50)
                ax.set_xlim(xlim)

            elif row == 2:
                xlim = ax.get_xlim()
                ax.plot(xlim, [x_x_thr]*2, color='grey', linestyle='solid', alpha=0.50)
                ax.plot(xlim, [o_x_thr]*2, color='grey', linestyle='dashed', alpha=0.50)
                ax.set_xlim(xlim)

            if col == 0:
                ylim = ax.get_ylim()
                ax.plot([x_logmag_thr]*2, ylim, color='grey', linestyle='solid', alpha=0.50)
                ax.plot([o_logmag_thr]*2, ylim, color='grey', linestyle='dashed', alpha=0.50)
                ax.set_ylim(ylim)

            elif col == 1:
                ylim = ax.get_ylim()
                ax.plot([x_o_thr]*2, ylim, color='grey', linestyle='solid', alpha=0.50)
                ax.plot([o_o_thr]*2, ylim, color='grey', linestyle='dashed', alpha=0.50)
                ax.set_ylim(ylim)

            elif col == 2:
                ylim = ax.get_ylim()
                ax.plot([x_x_thr]*2, ylim, color='grey', linestyle='solid', alpha=0.50)
                ax.plot([o_x_thr]*2, ylim, color='grey', linestyle='dashed', alpha=0.50)
                ax.set_ylim(ylim)

        # add 1D marginal distribution
        ax = plt.plt.subplot(num, num, num*row+row+1)

        X = data[row]

        for color, label1, label2, ect in selections:
            ectbins = min(100, max(10, int(0.5*np.sum(ect)**0.5)))
            selbins = min(100, max(10, int(0.5*np.sum(sel*ect)**0.5)))

            ax.hist(np.ravel(X[ect]), bins=ectbins, histtype='step', orientation='vertical', log=True, color=color)
            ax.hist(np.ravel(X[ect*sel]), bins=selbins, histtype='stepfilled', orientation='vertical', log=True, color=color, alpha=0.25)

        ax.set_xlabel(labels[row])
        if row != 0:
            ax.yaxis.tick_right()

        ylim = ax.get_ylim()
        if row == 0:
            ax.plot([x_logmag_thr]*2, ylim, color='grey', linestyle='solid', alpha=0.50)
            ax.plot([o_logmag_thr]*2, ylim, color='grey', linestyle='dashed', alpha=0.50)

        elif row == 1:
            ax.plot([x_o_thr]*2, ylim, color='grey', linestyle='solid', alpha=0.50)
            ax.plot([o_o_thr]*2, ylim, color='grey', linestyle='dashed', alpha=0.50)

        elif row == 2:
            ax.plot([x_x_thr]*2, ylim, color='grey', linestyle='solid', alpha=0.50)
            ax.plot([o_x_thr]*2, ylim, color='grey', linestyle='dashed', alpha=0.50)

        ax.set_ylim(ylim)

    #---

    fig.text(0.95, 0.95-0.025*(2*ind+2), 'identified X (%d)' % np.sum(mins*(logmag < x_logmag_thr)*(x < x_x_thr)*(o > x_o_thr)), ha='right', va='top', fontsize=8)
    fig.text(0.95, 0.95-0.025*(2*ind+3), 'identified X in coherent structure (%d)' % np.sum(mins*sel*(logmag < x_logmag_thr)*(x < x_x_thr)*(o > x_o_thr)), ha='right', va='top', fontsize=8)

    fig.text(0.95, 0.95-0.025*(2*ind+4), 'identified O (%d)' % np.sum(mins*(logmag < o_logmag_thr)*(x > o_x_thr)*(o < o_o_thr)), ha='right', va='top', fontsize=8)
    fig.text(0.95, 0.95-0.025*(2*ind+5), 'identified O in coherent structure (%d)' % np.sum(mins*sel*(logmag < o_logmag_thr)*(x > o_x_thr)*(o < o_o_thr)), ha='right', va='top', fontsize=8)

    #---

    for ax in fig.axes:
        ax.tick_params(
            left=True,
            right=True,
            top=True,
            bottom=True,
            direction='in',
            which='both',
        )

    plt.plt.subplots_adjust(
        left=0.10,
        right=0.95,
        bottom=0.10,
        top=0.95,
        hspace=0.03,
        wspace=0.03,
    )

    #---

    return fig

#------------------------

def oradii(mag0, mag1, x, y):
    """a simple estimate of the radius
    """
    abs_mag = (mag0**2 + mag1**2)**0.5

    ans = []
    for X, Y in zip(x, y):
        r = 0
        ave = +1
        while ave > 0.75: # FIXME ad hoc threshold
            r += 1 # move out one step

            # compute average
            ave = (+mag1[X+r,Y])/abs_mag[X+r,Y] + (-mag0[X,Y+r])/abs_mag[X,Y+r] \
                  + (-mag1[X-r,Y])/abs_mag[X-r,Y] + (mag0[X,Y-r])/abs_mag[X,Y-r]
            ave /= 4 # make this an average
            ave = np.abs(ave)

        ans.append((X, Y, r))

    return ans

#---

def oradius(mag0, mag1, x, y, title=None, delta=50):
    fig = plt.plt.figure(figsize=(5,18))

    ax1 = plt.plt.subplot(6,1,1)
    ax2 = plt.plt.subplot(6,1,2)
    ax3 = plt.plt.subplot(6,1,3)
    ax4 = plt.plt.subplot(6,1,4)
    ax5 = plt.plt.subplot(6,1,5)
    ax6 = plt.plt.subplot(6,1,6)

    #---

    abs_mag = (mag0**2 + mag1**2)**0.5
    nx, ny = mag0.shape

    kwargs = dict(marker='.', markersize=1, color='k', alpha=0.25, linestyle='none')

    # iterate over everything within this square
    i, j = np.meshgrid(range(max(0, x-delta), min(x+delta, nx)), range(max(0, y-delta), min(y+delta, ny)), indexing='ij')
    i = np.ravel(i)
    j = np.ravel(j)

    sel = np.logical_not((i==x)*(j==y)) # throw away the center point
    i = i[sel]
    j = j[sel]

    # compute displacement vector
    rx = i-x
    ry = j-y
    r = (rx**2 + ry**2)**0.5

    # compute components of mag field in radial and angular directions
    br = (mag0[i,j]*rx + mag1[i,j]*ry) / r
    bt = (mag0[i,j]*(-ry) + mag1[i,j]*rx) / r

    b = (br**2 + bt**2)**0.5

    # add to plots
    ax1.plot(r, b, **kwargs)
    ax2.plot(r, bt, **kwargs)
    ax3.plot(r, br, **kwargs)
    ax4.plot(r, np.abs(br/bt), **kwargs)
    ax5.plot(r, bt/b, **kwargs)
    ax6.plot(r, br/b, **kwargs)

    ax1.plot(0, (mag0[x,y]**2 + mag1[x,y]**2)**0.5, marker='x', markeredgecolor='k', markerfacecolor='none', markersize=4)
    ax1.plot([np.min(r), np.max(r)], [np.mean(abs_mag)]*2, color='m', alpha=1.0)

    #---

    inds = np.arange(1, min(max(min(x, nx-x), delta), max(min(y, ny-y), delta)))

    ave = (+mag1[x+inds,y])/abs_mag[x+inds,y] + (-mag[0,x,y+inds])/abs_mag[x,y+inds] \
          + (-mag[1,x-inds,y])/abs_mag[x-inds,y] + (mag[0,x,y-inds])/abs_mag[x,y-inds]
    ave /= 4 # make this an average

    ax5.plot(inds, ave, color='b')

    #---

    if title is not None:
        ax1.set_title(title)

    ylim = ax1.get_ylim()
    ax1.fill_between([0, 2**0.5], [ylim[0]]*2, [ylim[1]]*2, color='r', alpha=0.10)
    ax1.set_ylim(ylim)

    ax1.set_ylabel('$|B|$')
    plt.plt.setp(ax1.get_xticklabels(), visible=False)

    ax2.set_ylabel('$B_\\theta$')
    plt.plt.setp(ax2.get_xticklabels(), visible=False)

    ax3.set_ylabel('$B_r$')
    plt.plt.setp(ax3.get_xticklabels(), visible=False)

    ax4.set_yscale('log')
    ax4.set_ylabel('$B_r/B_\\theta$')
    plt.plt.setp(ax4.get_xticklabels(), visible=False)

    ax5.set_ylabel('$B_\\theta/|B|$')
    plt.plt.setp(ax5.get_xticklabels(), visible=False)

    ax6.set_ylabel('$B_r/|B|$')
    ax6.set_xlabel('$r$')

    for ax in fig.axes:
        ax.tick_params(
            left=True,
            right=True,
            top=True,
            bottom=True,
            which='both',
            direction='in',
        )

        ax.set_xlim(xmin=0, xmax=delta*2**0.5)

    plt.plt.subplots_adjust(
        left=0.15,
        right=0.95,
        top=0.95,
        bottom=0.02,
        hspace=0.03,
    )

    #---

    return fig

#-------------------------------------------------

parser = ArgumentParser()

#---

parser.add_argument('inpath', type=str)

#---

parser.add_argument('-w', '--wavelet', type=str, required=True)

parser.add_argument('--denoise', default=5.0, type=float)
parser.add_argument('--max-scale', default=None, type=int)

#---

parser.add_argument('-o', '--output-dir', default='.', type=str)
parser.add_argument('-t', '--tag', default='', type=str)

parser.add_argument('--figtype', default=[], type=str, action='append')
parser.add_argument('--dpi', default=200, type=float)

#---

parser.add_argument('-v', '--verbose', default=False, action='store_true')
parser.add_argument('-V', '--Verbose', default=False, action='store_true')

#---

args = parser.parse_args()

os.makedirs(args.output_dir, exist_ok=True)

if args.tag:
    args.tag = "_"+args.tag

if not args.figtype:
    args.figtype.append('png')

args.verbose |= args.Verbose

#-------------------------------------------------

basename = os.path.basename(args.inpath).split('.')[0] # used to construct output figure names

#-------------------------------------------------

# load magnetic field data

if args.verbose:
    print('loading magnetic field from: '+args.inpath)
mag = np.load(args.inpath)
_, nx, ny = mag.shape

#------------------------

# compute derived quantities

dvf = dv.DerivedVars(num_of_dims=2, bcs="00")

#-----------

# take the curl to get the current

if args.verbose:
    print('computing curr = curl(mag)')

curr = dvf.vector_curl(mag)
curr_ha = pywt.WaveletArray(curr, args.wavelet)

if args.Verbose:
    print('    denoising with thr=%.3f' % args.denoise)
curr_ha.denoise(args.denoise, max_scale=args.max_scale)

#-----------

if args.verbose:
    print('    computing gradient of magnetic field')
grad_mag = dvf.gradient_tensor(mag)

det = grad_mag[0,0]*grad_mag[1,1] - grad_mag[0,1]*grad_mag[1,0] # determinant of dBi/dxj
div = grad_mag[0,0] + grad_mag[1,1] # divergence: \sum_i dBi/dxi

#-----------

if args.verbose:
    print('    computing magnetic field magnitude')
abs_mag = np.sum(mag**2, axis=0)**0.5 # take the magnitude of the magnetic field vector

if args.verbose:
    print('    finding local extrema of magnetic field magnitude')
mins, maxs = extrema(abs_mag)

#-----------

if args.verbose:
    print('    computing test statistics for rotation symmetry')

o = np.empty((nx, ny), dtype=float)
o[0,:] = o[-1,:] = o[:,0] = o[:,-1] = np.nan # turn the edge points off

x = np.empty((nx, ny), dtype=float)
x[0,:] = x[-1,:] = x[:,0] = x[:,-1] = np.nan

for i in range(nx-2): # iterate through all points and test for symmetry in rotations of pi/2
    for j in range(ny-2):

        # compare the effect of rotating the field
        o[i+1,j+1] = \
            + (mag[0,i+1,j+2] - mag[1,i,j+1])**2 \
            + (mag[0,i+1,j+2] + mag[1,i+2,j+1])**2 \
            + (mag[0,i+1,j] - mag[1,i+2,j+1])**2 \
            + (mag[0,i+1,j] + mag[1,i,j+1])**2
        o[i+1,j+1] /= mag[0,i+1,j+2]**2 + mag[1,i,j+1]**2 + mag[0,i+1,j]**2 + mag[1,i+2,j+1]**2

        # compare the size of the gradient of fields in different directions
        # FIXME: may want to change this to something that's rotationally invariant (ie, maximize over orientation)?
        delta_perp = (mag[0,i+1,j+2] - mag[0,i+1,j])**2 + (mag[1,i+1,j+2] - mag[1,i+1,j])**2
        delta_parr = (mag[0,i+1,j+1] - mag[0,i,j+1])**2 + (mag[1,i+2,j+1] - mag[1,i,j+1])**2
        x[i+1,j+1] = delta_perp*delta_parr / (delta_perp**2 + delta_parr**2)

#-------------------------------------------------

_, nx, ny = mag.shape
xs = np.arange(nx)
ys = np.arange(ny)
X, Y = np.meshgrid(xs, ys, indexing='ij')

o_cent = mins * (np.log10(abs_mag) < o_logmag_thr) * (o < o_o_thr) * (x > o_x_thr)

Xo = X[o_cent]
Yo = Y[o_cent]

#-------------------------------------------------

# let's make some plots
if args.verbose:
    print('plotting')

# imshow of various fields with annotations
fig = imshow(curr, curr_ha.array, abs_mag, mag[0], mag[1], o, x, div, det, mins, maxs, aspect='auto')

figtmp = os.path.join(
    args.output_dir,
    '%s_magic-imshow%s' % \
        (basename, args.tag),
) + '.%s'

plt.save(fig, figtmp, args.figtype, dpi=args.dpi, verbose=args.verbose)
plt.close(fig)

#------------------------

# imshow of just log(abs_mag) with annotations
fig = imshow_mag(abs_mag, o, x, mins, aspect='equal', orad=oradii(mag[0], mag[1], Xo, Yo))

figtmp = os.path.join(
    args.output_dir,
    '%s_magic-mag%s' % \
        (basename, args.tag),
) + '.%s'

plt.save(fig, figtmp, args.figtype, dpi=args.dpi, verbose=args.verbose)
plt.close(fig)

#------------------------

# histograms of selection criteria
fig = hist(mins, maxs, np.abs(curr_ha.array > 0), abs_mag, o, x)

figtmp = os.path.join(
    args.output_dir,
    '%s_magic-hist%s' % \
        (basename, args.tag),
) + '.%s'

plt.save(fig, figtmp, args.figtype, dpi=args.dpi, verbose=args.verbose)
plt.close(fig)

#------------------------

# plot radial dependence of mag centered on O points

for (x, y) in zip(Xo, Yo):
    title = '(x, y) = (%d, %d)\n$\log o = %.3f$\n$\log|B| = %.3f$' % (x, y, np.log10(o[x,y]), np.log10(abs_mag[x,y]))

    fig = oradius(mag[0], mag[1], x, y, delta=100, title=title)

    figtmp = os.path.join(
        args.output_dir,
        '%s_magic-oradius-%06d-%06d%s' % \
            (basename, x, y, args.tag),
    ) + '.%s'

    plt.save(fig, figtmp, args.figtype, dpi=args.dpi, verbose=args.verbose)
    plt.close(fig)
