#!/bin/bash

### install supporting libraries
### Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

OPTDIR="../opt"
mkdir -p $OPTDIR

#------------------------

# install James Beattie's FLASH wrappers

pushd $OPTDIR
git clone https://github.com/AstroJames/PLASMAtools.git
popd
