#!/usr/bin/env python3

"""make a visualization of wavelet thresholding and associated statistics
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import os
import sys

import copy

import numpy as np

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

### non-standard libraries
from w4t.w4t import pywt
from w4t.utils import io
from w4t.plot import plane as plt

#-------------------------------------------------

denoise = 2.5 # this controls what is retained as "coherent"
thr = 1.5     # this controls the part of the coherent structure used to identify individual structures

#---

indexes = [1, 2, 3, 4, 5, 6] # for computing the spectrum

#---

wavelet = 'haar'

path = '../data/M05MA10/Turb_hdf5_plt_cnt_0050'
field = 'vort'

#max_edgelength = 512 # should be a power of 2
max_edgelength = 128

max_scale = 32 # let's just let the wavelet denoising do the heavy lifting. We can always make this cut later?

#---

cmap = 'PiYG'

cmap_coherent = cmap

output_dir = '.'
dpi = 100

#-------------------------------------------------

def aaa_imshow(
        ha,
        figtmp,
        norms=None,
        cmap='Reds',
        vmin=-2.0,
        vmax=2.0,
        label='',
        thr=0.0,
        structures=False,
        grand_tour=False,
        orthographic=False,
    ):
    print('iterating over scales')

    compute_norms = norms is None
    if compute_norms:
        norms = []

    ha.idecompose() # reset the decomposition

    ind = 0
    while ha.active[0] > 1:
        scales = '-'.join('%03d'%_ for _ in ha.scales)

        print('processing: '+scales)

        title = label # + '\nscale : ' + scales

        n0, n1, n2 = ha.active

        array_dict = dict()

        array_dict['aaa'] = ha.array[:n0, :n1, :n2]

        # get normalization
        if compute_norms:
            norm = np.std(array_dict['aaa'])
            norms.append(norm)
        else:
            norm = norms[ind]

        # approximate the mid-plane
        plane = 0.5*(array_dict['aaa'][:,:,n2//2] + array_dict['aaa'][:,:,n2//2-1]) / norm

        # plot the mid-plane
        fig = plt.plt.figure(figsize=(5,5))
        ax = fig.add_axes([0.05, 0.01, 0.90, 0.90])

        ax.imshow(
            plane,
            cmap=cmap,
            vmax=vmax,
            vmin=vmin,
            origin='lower',
            extent=(0, 1, 0, 1),
        )

        # decorate
        fig.suptitle(title, fontsize=10)

        ax.set_xticks([]) # remove any ticks
        ax.set_yticks([])

        # save
        plt.save(fig, (figtmp%scales)+'.%s', ['png'], dpi=dpi, verbose=True)
        plt.close(fig)

        #---

        # plot a histogram of values within plane

        fig = plt.plt.figure()
        ax = fig.gca()

        _, bins, _ = ax.hist(np.abs(plane.flatten()), bins=max(100, int(0.5*(n0*n1)**0.5)), histtype='step', density=True)
        ax.hist(np.abs(plane.flatten()), bins=bins, histtype='step', density=True, cumulative=True)

        ylim = ax.get_ylim()
        ax.plot([thr]*2, ylim, color='k', alpha=0.5)
        ax.set_ylim(ylim)

        ax.set_xlabel('abs(pixel coefficient)')

        # save
        plt.save(fig, (figtmp%scales+'_hist')+'.%s', ['png'], dpi=dpi, verbose=True)
        plt.close(fig)

        #---

        if grand_tour: # plot every plane separately
            print('plotting grand tour')
            for axis, (n, x) in enumerate([(n0, 'x'), (n1, 'y'), (n2, 'z')]):
                for xnd in range(n):
                    plane = np.take(array_dict['aaa'], xnd, axis=axis) / norm

                    fig = plt.plt.figure(figsize=(5,5))
                    ax = fig.add_axes([0.05, 0.01, 0.90, 0.90])

                    ax.imshow(
                        plane,
                        cmap=cmap,
                        vmax=vmax,
                        vmin=vmin,
                        origin='lower',
                        extent=(0, 1, 0, 1),
                    )

                    # decorate
                    fig.suptitle(title + '\n$%s=%d$'%(x,xnd), fontsize=10)

                    ax.set_xticks([]) # remove any ticks
                    ax.set_yticks([])

                    # save
                    plt.save(fig, (figtmp%scales)+('-%s-%03d'%(x,xnd))+'.%s', ['png'], dpi=dpi, verbose=True)
                    plt.close(fig)

        #---

        if orthographic and (ha.ndim==3):
            print('plotting orthographic views')
            levels = copy.copy(ha.levels) # make a copy so we can reset

            fig = plt.plt.figure(figsize=(10,10))

            for ax, axis, xlabel, ylabel in [
                    (plt.plt.subplot(2,2,1), 1, None, 'z'),
                    (plt.plt.subplot(2,2,3), 2, 'y', 'x'),
                    (plt.plt.subplot(2,2,4), 0, 'z', None),
                ]:
                ha.decompose(axis=axis) # collapse along one axis
                a = np.take(ha.approx, 0, axis=axis)
                vlim = np.max(np.abs(a))

                ax.imshow(
                    a,
                    cmap=cmap,
                    vmax=+vlim,
                    vmin=-vlim,
                    origin='lower',
                    extent=(0, 1, 0, 1),
                )

                ax.set_xticks([]) # remove any ticks
                ax.set_yticks([])

                ax.set_xlabel(xlabel)
                ax.set_ylabel(ylabel)

                ha.set_levels(levels)

            # decorate
            fig.suptitle(title, fontsize=10)

            plt.plt.subplots_adjust(
                left=0.05,
                right=0.95,
                bottom=0.05,
                top=0.95,
                hspace=0.01,
                wspace=0.01,
            )

            # save
            plt.save(fig, (figtmp%scales)+'-ortho'+'.%s', ['png'], dpi=dpi, verbose=True)
            plt.close(fig)

        #---

        if structures: # identify structures and make separate plots for each
#            print('identifying clusters in 2D midplane')
#            sel = np.abs(plane) > thr # which pixels we consider in 2D

            print('identifying clusters in full 3D box')
            sel = np.abs(array_dict['aaa']/norm) > thr # which pixels we consider in 3D

            clusters = ha.structures(sel)
            clusters.sort(key=lambda x: -len(x)) # biggest first

            num_clusters = len(clusters)
            print('    found %d clusters' % num_clusters)

            ect = 0.5*(sel[:,:,n2//2].astype(int) + sel[:,:,n2//2-1].astype(int)) # just the midplane

            for cnd, cluster in enumerate(clusters):
                num_pix = len(cluster)
                sys.stdout.write('\r    cluster : %d / %d (len = %d / %d)' % (cnd, num_clusters, num_pix, n0*n1*n2))
                sys.stdout.flush()

#                a = np.zeros((n0, n1), dtype=float) # 2D representation
                a = np.zeros((n0, n1, n2), dtype=float) # 3D representation
                a[:] = np.nan

                cluster = tuple(np.transpose(cluster)) # make this so an array can understand it
#                a[cluster] = plane[cluster] # 2D
                a[cluster] = array_dict['aaa'][cluster] / norm # 3D

                plane = np.where( # deal with nans in neighboring planes
                    np.isnan(a[:,:,n2//2]),
                    np.where(
                        np.isnan(a[:,:,n2//2-1]),
                        np.nan,
                        a[:,:,n2//2-1],
                    ),
                    np.where(
                        np.isnan(a[:,:,n2//2-1]),
                        a[:,:,n2//2],
                        0.5*(a[:,:,n2//2] + a[:,:,n2//2-1]),
                    ),
                )

                if np.all(np.isnan(plane)):
                    sys.stdout.write('\r    nothing to show!')

                else:
                    sys.stdout.write('\r    plotting!\n')

                    fig = plt.plt.figure(figsize=(5,5))
                    ax = fig.add_axes([0.05, 0.01, 0.90, 0.90])

                    # plot the overall set of pixels selected
                    ax.imshow(
                        ect,
                        cmap='Greys',
                        vmax=1,
                        vmin=0,
                        origin='lower',
                        extent=(0, 1, 0, 1),
                    )

                    # plot only this cluster
                    ax.imshow(
                        plane,
                        cmap=cmap,
                        vmax=vmax,
                        vmin=vmin,
                        origin='lower',
                        extent=(0, 1, 0, 1),
                    )

                    # decorate
                    fig.suptitle('cluster %d (%d pixels)' % (cnd, num_pix), fontsize=10)

                    ax.set_xticks([]) # remove any ticks
                    ax.set_yticks([])

                    # save
                    plt.save(fig, (figtmp%scales + '_cluster-%03d'%cnd)+'.%s', ['png'], dpi=dpi, verbose=True)
                    plt.close(fig)

                #---

                if orthographic and (ha.ndim==3) and (num_pix > 100):
                    print('plotting orthographic views')
                    
                    _ha = pywt.PyWaveletArray(np.where(np.isnan(a), 0.0, a), wavelet)
                    levels = copy.copy(_ha.levels) # make a copy so we can reset

                    fig = plt.plt.figure(figsize=(10,10))

                    for ax_ind, axis, xlabel, ylabel, trans in [
                            (1, 1, 'x', 'z', True),
                            (3, 2, 'x', 'y', True),
                            (4, 0, 'z', 'y', False),
                        ]:
                        ax = plt.plt.subplot(2,2,ax_ind)
                        _ha.decompose(axis=axis) # collapse along one axis

                        b = np.take(_ha.approx, 0, axis=axis)
                        if trans:
                            b = np.transpose(b)
                        vlim = np.max(np.abs(b))

                        ax.imshow(
                            b,
                            cmap=cmap,
                            vmax=+vlim,
                            vmin=-vlim,
                            origin='lower',
                            extent=(0, 1, 0, 1),
                        )

                        ax.set_xticks([]) # remove any ticks
                        ax.set_yticks([])

                        ax.set_xlabel(xlabel)
                        if ax_ind <= 2:
                            ax.xaxis.set_label_position('top')

                        ax.set_ylabel(ylabel)
                        if (ax_ind % 2) == 0:
                            ax.yaxis.set_label_position('right')

                        _ha.set_levels(levels)

                    # decorate
                    fig.suptitle(title, fontsize=10)

                    plt.plt.subplots_adjust(
                        left=0.05,
                        right=0.95,
                        bottom=0.05,
                        top=0.95,
                        hspace=0.01,
                        wspace=0.01,
                    )

                    # save
                    plt.save(fig, (figtmp%scales)+('-ortho_cluster-%03d'%cnd)+'.%s', ['png'], dpi=dpi, verbose=True)
                    plt.close(fig)

                #---

                if grand_tour and (num_pix > 100): # FIXME? arbitrary cut-off for how big the cluster has to be to get a grand tour...
                    sys.stdout.write('\r    plotting grand tour!\n')

                    for axis, (n, x) in enumerate([(n0, 'x'), (n1, 'y'), (n2, 'z')]):
                        for xnd in range(n):
                            fig = plt.plt.figure(figsize=(5,5))
                            ax = fig.add_axes([0.05, 0.01, 0.90, 0.90])

                            # plot the overall set of pixels selected
                            ax.imshow(
                                np.take(sel, xnd, axis=axis),
                                cmap='Greys',
                                vmax=1,
                                vmin=0,
                                origin='lower',
                                extent=(0, 1, 0, 1),
                            )

                            # plot only this cluster
                            ax.imshow(
                                np.take(a, xnd, axis=axis),
                                cmap=cmap,
                                vmax=vmax,
                                vmin=vmin,
                                origin='lower',
                                extent=(0, 1, 0, 1),
                            )

                            # decorate
                            fig.suptitle('cluster %d (%d pixels)\n$%s=%d$' % (cnd, num_pix, x, xnd), fontsize=10)

                            ax.set_xticks([]) # remove any ticks
                            ax.set_yticks([])

                            # save
                            plt.save(
                                fig,
                                (figtmp%scales + '_cluster-%03d-%s-%03d'%(cnd,x,xnd))+'.%s',
                                ['png'],
                                dpi=dpi,
                                verbose=True,
                            )
                            plt.close(fig)

            sys.stdout.write('\n')
            sys.stdout.flush()

        #---

        del array_dict

        ha.dwt() # decompose
        ind += 1

    return norms

#-------------------------------------------------
#
# NOW DO THINGS
#
#-------------------------------------------------

basename = os.path.basename(path).split('.')[0]

data = io.load([field], path=path, max_edgelength=max_edgelength, verbose=True)[field]

#---

#data = np.sum(data**2, axis=0)**0.5 # magnitude
#label = r'$\left| \vec{\omega} = \vec{\nabla} \times \vec{u} \right|$'

data = data[0]
label = r'$\omega_x$'

vmin = -3.0
vmax = +3.0

#-------------------------------------------------

# instantiate wavelet object
ha = pywt.PyWaveletArray(data, wavelet)

#---

# make images of the flow at different scales (approx coefficients)
figtmp = os.path.join(output_dir, '%s_%s_%s_imshow' % (basename, field, '%s'))

norms = aaa_imshow(
    ha,
    figtmp,
    norms=None,
    vmin=vmin,
    vmax=vmax,
    cmap=cmap,
    label=label,
    orthographic=True,
    grand_tour=False,
)

#------------------------

# compute spectrum
print('computing spectrum of the full flow')
scales, mom, cov = ha.moments(index=indexes, use_abs=True, remove_wavelet_normalization=True)
ha.idecompose() # reset the decomposition

#-------------------------------------------------

# make images of flow after denoising

print('denoising')
ha.denoise(denoise, smooth=False, max_scale=max_scale)

#---

# make images of selected flow
aaa_imshow(
    ha,
    figtmp+'-denoise',
    norms=norms,
    vmin=vmin,
    vmax=vmax,
    cmap=cmap_coherent,
    label=label,
    orthographic=True,
    grand_tour=False,
    structures=True,
    thr=thr,
)

#------------------------

# compute spectrum
print('computing spectrum of coherent structures')
dn_scales, dn_mom, dn_cov = ha.moments(index=indexes, use_abs=True, remove_wavelet_normalization=True)
ha.idecompose() # reset the decomposition

#-------------------------------------------------

# make image of spectrum

print('plotting structure functions (moments of detail coefficients)')

fig = plt.plt.figure(figsize=(5,3))
ax = fig.add_axes([0.15, 0.15, 0.80, 0.80])

# plot
for ind, index in enumerate(indexes):

    # full flow
    color = ax.plot(scales[:,0], mom[:,ind]**(1/index), alpha=0.5, marker='.', label='$p=%d$'%index)[0].get_color()
    for a, b, c in zip(scales[:,0], mom[:,ind], cov[:,ind,ind]**0.5):
        ax.plot([a]*2, [(b-c)**(1/index), (b+c)**(1/index)], color=color, alpha=0.50)

    # coherent structures?
    ax.plot(dn_scales[:,0], dn_mom[:,ind]**(1/index), color=color, linestyle='dashed', alpha=0.5)
#    for a, b, c in zip(scales[:,0], mom[:,ind], cov[:,ind,ind]**0.5):
#        ax.plot([a]*2, [(b-c)**(1/index), (b+c)**(1/index)], color=color, alpha=0.50)


# decorate
ax.set_xlabel('scale')
ax.set_ylabel(r'$\left< d^{p}_{\vec{x},s}\right>^{1/p}_{\vec{x}}$')

ax.set_yscale('log')
ax.set_ylim(ymin=1e0, ymax=6e3)

ax.set_xscale('log')
ax.set_xticks(scales[::-1,0])
ax.set_xticklabels(['%d'%_ for _ in ax.get_xticks()])
ax.set_xlim(xmin=scales[-2,0], xmax=scales[0,0])

ax.tick_params(
    left=True,
    right=True,
    bottom=True,
    top=True,
    direction='in',
    which='both',
)

ax.legend(loc='lower left', ncol=2)

# save
figtmp = os.path.join(output_dir, '%s_%s_spectrum' % (basename, field)) + '.%s'

plt.save(fig, figtmp, ['png'], dpi=dpi, verbose=True)
plt.close(fig)
