#!/usr/bin/env python3

import numpy as np
import copy
from w4t.pywt import WaveletArray

import time

#-------------------------------------------------

np.random.seed(123)

#-------------------------------------------------

data = np.random.normal(size=(10,)*2)

ha = WaveletArray(data, 'haar')

#------------------------

thr = 1.0
sel = np.abs(ha.approx) > thr
print(sel)

#------------------------

print('testing ability to select a pixel from a boolean array')

pix = ha._sel2pix(sel)
print(pix)

#------------------------

print('testing ability to identify neighbors')

neighbors = ha._pix2neighbors(pix, sel.shape)
print('neighbors')
for neighbor in neighbors:
    print('    ', neighbor)

#------------------------

print('testing ability to find a cluster that includes a pixel')

cluster, new = ha._pix2cluster(pix, copy.copy(sel))
print(sel)
print(new)
print('cluster')
for _ in cluster:
    print('    ', _)

#------------------------

print('testing ability to find all clusters')

clusters = ha._structures(copy.copy(sel))
for cnd, cluster in enumerate(clusters):
    print('cluster %d' % cnd)
    for _ in cluster:
        print('    ', _)

    print(sel[tuple(np.transpose(cluster))])

    if len(cluster) > 1:
        for ind in range(len(cluster)):
            dist = np.sum((cluster[ind]-cluster)**2, axis=1)
            dist = list(dist[:ind])+list(dist[ind+1:])

            if cnd < len(clusters)-1:
                ance = [np.min(np.sum((cluster[ind]-other)**2, axis=1)) for other in clusters[cnd+1:]]
                print(    ind, np.min(dist), np.min(ance))
            else:
                print(    ind, np.min(dist))

#------------------------

# test multiprocessing

print('testing multiprocessing')

t0 = time.time()
sc = ha.structures(thr=thr)
print('single-core structure identification:', time.time()-t0)

t0 = time.time()
mp = ha.structures(thr=thr, num_proc=4)
print('multiprocessing structure identification:', time.time()-t0)

for dim in range(ha.ndim):
    sc = [struc[np.argsort(struc[:,-(dim+1)])] for struc in sc] # order the indiv pixels within each structure
    sc.sort(key=lambda x:x[0,-(dim+1)]) # order structures

    mp = [struc[np.argsort(struc[:,-(dim+1)])] for struc in mp] # order the indiv pixels within each structure
    mp.sort(key=lambda x:x[0,-(dim+1)]) # order structures

assert len(sc) == len(mp), 'identified different numbers of structures'

for ind in range(len(sc)):

    for jnd, pix in enumerate(sc[ind]):
        if np.any(np.all(pix==sc[ind][jnd+1:], axis=1)):
            raise RuntimeError('pix repeated in sc!', pix)

    for jnd, pix in enumerate(mp[ind]):
        if np.any(np.all(pix==mp[ind][jnd+1:], axis=1)):
            raise RuntimeError('pix repeated in mp!', pix)

    assert len(sc[ind]) == len(mp[ind]), 'identified structures contain different numbers of pixels'

    for pix in sc[ind]:
        assert np.sum(np.all(pix==mp[ind], axis=1)) == 1, 'pixel mismatch or repeated pixel'

#------------------------


# check pix2structures vs _structures

t0 = time.time()
s2s = ha._structures(sel)
print('_structures:    ', time.time()-t0)

t0 = time.time()
p2s = ha._pix2structures(np.transpose(np.nonzero(sel)), max_sep=1.5)
print('_pix2structures:', time.time()-t0)

for cnd, cluster in enumerate(p2s):
    if len(cluster) > 1:
        for ind in range(len(cluster)):
            dist = np.sum((cluster[ind]-cluster)**2, axis=1)
            dist = list(dist[:ind])+list(dist[ind+1:])
            assert min(dist) <= 2

            if cnd < len(p2s)-1:
                ance = [np.min(np.sum((cluster[ind]-other)**2, axis=1)) for other in p2s[cnd+1:]]
                assert np.min(ance) > 2

#---

for dim in range(ha.ndim):
    s2s = [struc[np.argsort(struc[:,-(dim+1)])] for struc in s2s] # order the indiv pixels within each structure
    s2s.sort(key=lambda x:x[0,-(dim+1)]) # order structures

    p2s = [struc[np.argsort(struc[:,-(dim+1)])] for struc in p2s] # order the indiv pixels within each structure
    p2s.sort(key=lambda x:x[0,-(dim+1)]) # order structures

assert len(s2s) == len(p2s), 'identified different numbers of structures'

for ind in range(len(s2s)):

    for jnd, pix in enumerate(s2s[ind]):
        if np.any(np.all(pix==s2s[ind][jnd+1:], axis=1)):
            raise RuntimeError('pix repeated in s2s!', pix)

    for jnd, pix in enumerate(p2s[ind]):
        if np.any(np.all(pix==p2s[ind][jnd+1:], axis=1)):
            raise RuntimeError('pix repeated in p2s!', pix)

    assert len(sc[ind]) == len(mp[ind]), 'identified structures contain different numbers of pixels'

    for pnd in range(len(s2s[ind])):
        assert np.sum(np.all(s2s[ind][pnd]==p2s[ind], axis=1)) == 1, 'pixel mismatch: cluster %d pixel %d' % (ind, pnd)
