#!/bin/bash

# make a short movie out of a sequence of png files
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

base="Turb_hdf5_plt_cnt_0050_vort"

for scale in "001-001-001"
do

    base_scale="${base}_${scale}_imshow"

    for denoise in "" # "-denoise"
    do

        base_scale_denoise="${base_scale}${denoise}"

        for dim in "x" # "y" "z"
        do

            basename="${base_scale_denoise}-${dim}"

            ffmpeg \
                -framerate 25 \
                -i ${basename}-%03d.png \
                -c:v libx264 \
                -pix_fmt yuv420p \
                ${basename}.mp4 \
            || exit 1

            ffmpeg \
                -i ${basename}.mp4 \
                -loop -1 \
                ${basename}.gif \
            || exit 1

        done
    done
done
